# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
